apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
  description: A collection of all services that the FireHydrant catalog should point to an ingest
spec:
  type: url
  targets:
    - https://github.com/MattHughesEE/mh-services-*/blob/main/service-catalog.yaml
